### PR TITLE
Passing deps to builder

### PR DESCRIPTION
**Pull request by vicentelyrio**

### CODE REVIEW

**Review by danielbdias — APPROVED** [review]
It seems pretty ok for me! Just to understand the context better, are these changes needed to do more tests in Children components @vicentelyrio ?

**Comment by danielbdias** [comment]
Just one problem... The CI is broken due some weird problem in standard.js related with Node.js version. It's good to fix this before merging this PR. @vicentelyrio have you tested this code against which version of Node.js?

**Comment by vicentelyrio** [comment]
Hey @danielbdias, my goal here is to be able to access Entity dependencies and pass them to child entities in the `builder`

**Comment by danielbdias** [comment]
@MatheusRibeiro @l4mb22 do you agree with the changes? Can I merge these changes?

**Comment by vicentelyrio** [comment]
I was thinking and maybe Speck could also expose all the data on the builder too. Something like

`builder: (fieldData, Type, data, arguments) => {}`

Although it's a very awkward signature, this way we can build a child entity based on the value of any of entity's field:

```
builder: (fieldData, Type, data, arguments) => {
  const otherField = data.someOtherField
  
  return !!otherField ? new Type(data) : new Error()
}
```

**Comment by albertossilva** [comment]
👍

**Comment by vicentelyrio** [comment]
cri cri

**Review by danielbdias — APPROVED** [review]

**Review by MatheusRibeiro — APPROVED** [review]

**Review by albertossilva — APPROVED** [review]
Its ok form me.

**Pull request merged**
